import type {BadgeDefinition} from '@/types/badge.types';

/**
 * Badge catalog — keep existing IDs stable (persisted in user_badges / featured / notifications).
 * Order within each category: easiest → hardest.
 */
export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // --- STREAK ---
  {
    id: 'streak_starter_3',
    name: 'Starter',
    emoji: '🔥',
    description: '3 træningsdage i træk',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 3,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'streak_locked_in_7',
    name: 'Locked In',
    emoji: '🔒',
    description: '7 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 7,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'streak_no_excuses_14',
    name: 'No Excuses',
    emoji: '🧱',
    description: '14 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 14,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'streak_disciplined_30',
    name: 'Disciplined',
    emoji: '🛡️',
    description: '30 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 30,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'streak_unstoppable_60',
    name: 'Unstoppable',
    emoji: '⚡',
    description: '60 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 60,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'streak_legendary_100',
    name: 'Legendary',
    emoji: '🏆',
    description: '100 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 100,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'streak_unbreakable_365',
    name: 'Unbreakable',
    emoji: '💎',
    description: '365 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 365,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- CHECK-IN (anti-dup <30 min mellem credits) ---
  {
    id: 'checkin_first_1',
    name: 'First Check-in',
    emoji: '✅',
    description: 'Dit første tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 1,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'checkin_showing_5',
    name: 'Showing Up',
    emoji: '📍',
    description: '5 tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 5,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'checkin_consistent_25',
    name: 'Consistent',
    emoji: '💪',
    description: '25 tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 25,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'checkin_regular_50',
    name: 'Regular',
    emoji: '🏋️',
    description: '50 tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 50,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'checkin_always_100',
    name: 'Always There',
    emoji: '🎯',
    description: '100 tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 100,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'checkin_veteran_200',
    name: 'Gym Veteran',
    emoji: '🦍',
    description: '200 tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 200,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'checkin_gymrat_300',
    name: 'Gym Rat',
    emoji: '🐀',
    description: '300 tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 300,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'checkin_legend_500',
    name: 'Gym Legend',
    emoji: '🐐',
    description: '500 tjek-ind',
    category: 'checkin',
    requirement_type: 'total_check_ins',
    requirement_value: 500,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- SESSIONS (kun ≥5 min) ---
  {
    id: 'sessions_first_1',
    name: 'First Step',
    emoji: '🥇',
    description: '1 træning registreret',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 1,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'sessions_routine_10',
    name: 'Routine Started',
    emoji: '🔁',
    description: '10 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 10,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'sessions_habit_50',
    name: 'Habit Built',
    emoji: '🧠',
    description: '50 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 50,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'sessions_addicted_100',
    name: 'Addicted',
    emoji: '🧲',
    description: '100 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 100,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'sessions_committed_150',
    name: 'Committed',
    emoji: '✊',
    description: '150 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 150,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'sessions_machine_250',
    name: 'Machine',
    emoji: '🤖',
    description: '250 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 250,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'sessions_built_different_500',
    name: 'Built Different',
    emoji: '🦾',
    description: '500 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 500,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- STRENGTH / WORKOUT LOG ---
  {
    id: 'strength_first_set_1',
    name: 'First Set',
    emoji: '✏️',
    description: 'Log dit første sæt i Workout Log',
    category: 'records',
    requirement_type: 'total_logged_sets',
    requirement_value: 1,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'strength_century_100',
    name: 'Century Club',
    emoji: '💯',
    description: '100 loggede sæt',
    category: 'records',
    requirement_type: 'total_logged_sets',
    requirement_value: 100,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'strength_first_pr_1',
    name: 'First PR',
    emoji: '🎖️',
    description: 'Din første PR i Workout Log',
    category: 'records',
    requirement_type: 'total_pr_events',
    requirement_value: 1,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'strength_pr_machine_10',
    name: 'PR Machine',
    emoji: '🚀',
    description: '10 PR-events',
    category: 'records',
    requirement_type: 'total_pr_events',
    requirement_value: 10,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'strength_record_breaker_50',
    name: 'Record Breaker',
    emoji: '💥',
    description: '50 PR-events',
    category: 'records',
    requirement_type: 'total_pr_events',
    requirement_value: 50,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- TIME (minutter, kun sessioner ≥5 min) ---
  {
    id: 'time_warmup_300',
    name: 'Warmup',
    emoji: '⏱️',
    description: '300 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 300,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'time_builder_1000',
    name: 'Builder',
    emoji: '🏗️',
    description: '1.000 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 1000,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'time_dedicated_2500',
    name: 'Dedicated',
    emoji: '📈',
    description: '2.500 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 2500,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'time_iron_5000',
    name: 'Iron Hours',
    emoji: '⛓️',
    description: '5.000 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 5000,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'time_grinder_10000',
    name: 'Grinder',
    emoji: '⏳',
    description: '10.000 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 10000,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'time_elite_25000',
    name: 'Elite',
    emoji: '👑',
    description: '25.000 min træning i alt',
    category: 'elite',
    requirement_type: 'total_time_minutes',
    requirement_value: 25000,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'time_immortal_50000',
    name: 'Immortal',
    emoji: '♾️',
    description: '50.000 min træning i alt',
    category: 'elite',
    requirement_type: 'total_time_minutes',
    requirement_value: 50000,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'time_eternal_100000',
    name: 'Eternal',
    emoji: '✨',
    description: '100.000 min træning i alt',
    category: 'elite',
    requirement_type: 'total_time_minutes',
    requirement_value: 100000,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- MESSAGING ---
  {
    id: 'msg_first_1',
    name: 'First Message',
    emoji: '💬',
    description: 'Send din første besked',
    category: 'messaging',
    requirement_type: 'total_messages_sent',
    requirement_value: 1,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'msg_active_unique_25',
    name: 'Active Talker',
    emoji: '🗣️',
    description: 'Skriv til 25 forskellige personer (DM-tråde)',
    category: 'messaging',
    requirement_type: 'unique_dm_recipients',
    requirement_value: 25,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'msg_social_rep_100',
    name: 'Social Rep',
    emoji: '📣',
    description: '100 beskeder sendt',
    category: 'messaging',
    requirement_type: 'total_messages_sent',
    requirement_value: 100,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'msg_chat_legend_500',
    name: 'Gym Chat Legend',
    emoji: '📢',
    description: '500 beskeder sendt',
    category: 'messaging',
    requirement_type: 'total_messages_sent',
    requirement_value: 500,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- SOCIAL ---
  {
    id: 'social_partner_1',
    name: 'First Friend',
    emoji: '👥',
    description: 'Din første ven på Gymly',
    category: 'social',
    requirement_type: 'friends_count',
    requirement_value: 1,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'social_squad_5',
    name: 'Squad',
    emoji: '👊',
    description: '5 venner',
    category: 'social',
    requirement_type: 'friends_count',
    requirement_value: 5,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'social_community_15',
    name: 'Community',
    emoji: '🌐',
    description: '15 venner',
    category: 'social',
    requirement_type: 'friends_count',
    requirement_value: 15,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'social_connector_25',
    name: 'Connector',
    emoji: '🤝',
    description: '25 venner',
    category: 'social',
    requirement_type: 'friends_count',
    requirement_value: 25,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'social_network_50',
    name: 'Network',
    emoji: '🕸️',
    description: '50 venner',
    category: 'social',
    requirement_type: 'friends_count',
    requirement_value: 50,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- PLANLAGT ---
  {
    id: 'planned_planner_5',
    name: 'Planner',
    emoji: '📝',
    description: '5 gennemførte planer (tjek ind efter planens tid)',
    category: 'planned',
    requirement_type: 'planned_workouts_completed_valid',
    requirement_value: 5,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'planned_organized_10',
    name: 'Getting Organized',
    emoji: '📋',
    description: '10 gennemførte planer',
    category: 'planned',
    requirement_type: 'planned_workouts_completed_valid',
    requirement_value: 10,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'planned_on_schedule_25',
    name: 'On Schedule',
    emoji: '⏰',
    description: '25 gennemførte planer',
    category: 'planned',
    requirement_type: 'planned_workouts_completed_valid',
    requirement_value: 25,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'planned_master_50',
    name: 'Master Planner',
    emoji: '🗓️',
    description: '50 gennemførte planer',
    category: 'planned',
    requirement_type: 'planned_workouts_completed_valid',
    requirement_value: 50,
    rarity: 'legendary',
    is_hidden: false,
  },

  // --- VANER ---
  {
    id: 'habit_early_bird_5',
    name: 'Early Bird',
    emoji: '🌅',
    description: '5 tidlige tjek-ind (før kl. 08, dansk tid)',
    category: 'habits',
    requirement_type: 'early_check_ins',
    requirement_value: 5,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'habit_sunrise_15',
    name: 'Sunrise Regular',
    emoji: '🏞️',
    description: '15 tidlige tjek-ind (før kl. 08, dansk tid)',
    category: 'habits',
    requirement_type: 'early_check_ins',
    requirement_value: 15,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'habit_morning_machine_30',
    name: 'Morning Machine',
    emoji: '☀️',
    description: '30 tidlige tjek-ind (før kl. 08, dansk tid)',
    category: 'habits',
    requirement_type: 'early_check_ins',
    requirement_value: 30,
    rarity: 'legendary',
    is_hidden: false,
  },
  {
    id: 'habit_night_grinder_5',
    name: 'Night Grinder',
    emoji: '🌙',
    description: '5 sene tjek-ind (efter kl. 22, dansk tid)',
    category: 'habits',
    requirement_type: 'late_check_ins',
    requirement_value: 5,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'habit_after_hours_15',
    name: 'After Hours',
    emoji: '🌃',
    description: '15 sene tjek-ind (efter kl. 22, dansk tid)',
    category: 'habits',
    requirement_type: 'late_check_ins',
    requirement_value: 15,
    rarity: 'epic',
    is_hidden: false,
  },
  {
    id: 'habit_midnight_30',
    name: 'Midnight Muscle',
    emoji: '🌌',
    description: '30 sene tjek-ind (efter kl. 22, dansk tid)',
    category: 'habits',
    requirement_type: 'late_check_ins',
    requirement_value: 30,
    rarity: 'legendary',
    is_hidden: false,
  },
];

export const BADGE_BY_ID: Record<string, BadgeDefinition> = Object.fromEntries(
  BADGE_DEFINITIONS.map(b => [b.id, b]),
);
