import type {BadgeDefinition} from '@/types/badge.types';

/** Fase 1 — nem at udvide: tilføj rækker her */
export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // STREAK
  {
    id: 'streak_starter_3',
    name: 'Starter',
    emoji: '🔥',
    description: '3 træningsdage i træk',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 3,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'streak_on_fire_7',
    name: 'On Fire',
    emoji: '🔥🔥',
    description: '7 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 7,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'streak_locked_in_14',
    name: 'Locked In',
    emoji: '💎',
    description: '14 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 14,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'streak_disciplined_30',
    name: 'Disciplined',
    emoji: '👑',
    description: '30 dages streak',
    category: 'streak',
    requirement_type: 'streak_days',
    requirement_value: 30,
    rarity: 'epic',
    is_hidden: false,
  },
  // TIME (minutter)
  {
    id: 'time_warmup_300',
    name: 'Warmup',
    emoji: '⏱️',
    description: '300 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 300,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'time_serious_1500',
    name: 'Getting Serious',
    emoji: '⏱️',
    description: '1500 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 1500,
    rarity: 'rare',
    is_hidden: false,
  },
  {
    id: 'time_dedicated_6000',
    name: 'Dedicated',
    emoji: '⏱️',
    description: '6000 min træning i alt',
    category: 'time',
    requirement_type: 'total_time_minutes',
    requirement_value: 6000,
    rarity: 'epic',
    is_hidden: false,
  },
  // SESSIONS
  {
    id: 'sessions_first_1',
    name: 'First Step',
    emoji: '🥇',
    description: '1 træning registreret',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 1,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'sessions_routine_10',
    name: 'Routine Started',
    emoji: '🏋️',
    description: '10 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 10,
    rarity: 'common',
    is_hidden: false,
  },
  {
    id: 'sessions_habit_50',
    name: 'Habit Built',
    emoji: '🔁',
    description: '50 træninger',
    category: 'sessions',
    requirement_type: 'total_sessions',
    requirement_value: 50,
    rarity: 'rare',
    is_hidden: false,
  },
  // SOCIAL
  {
    id: 'social_partner_1',
    name: 'Training Partner',
    emoji: '👥',
    description: 'Træn med mindst én ven',
    category: 'social',
    requirement_type: 'friends_count',
    requirement_value: 1,
    rarity: 'common',
    is_hidden: false,
  },
];

export const BADGE_BY_ID: Record<string, BadgeDefinition> = Object.fromEntries(
  BADGE_DEFINITIONS.map(b => [b.id, b]),
);
