/**
 * Local mock catalogue approximating shop.gymlyapp.com inventory shape.
 * Images intentionally empty — UI uses replaceable placeholders until Shopify CDN.
 * Destination URLs are safe HTTPS test destinations (no secrets).
 */
import type {ShopBrand, ShopProduct} from '@/types/shop.types';

export const MOCK_SHOP_BRANDS: readonly ShopBrand[] = [
  {id: 'brand-gymshark', name: 'Gymshark'},
  {id: 'brand-myprotein', name: 'Myprotein'},
  {id: 'brand-nike', name: 'Nike Training'},
  {id: 'brand-theragun', name: 'Therabody'},
  {id: 'brand-rogue', name: 'Rogue'},
  {id: 'brand-gymly', name: 'Gymly'},
] as const;

function iso(daysAgo: number): string {
  return new Date(Date.now() - daysAgo * 86_400_000).toISOString();
}

export const MOCK_SHOP_PRODUCTS: readonly ShopProduct[] = [
  {
    id: 'prod_gs_seamless_legging',
    handle: 'gymshark-seamless-legging',
    title: 'Seamless Training Leggings',
    description:
      'High-waist seamless leggings with squat-proof fabric and a supportive waistband for heavy sessions.',
    brand: 'Gymshark',
    brandId: 'brand-gymshark',
    category: 'activewear',
    tags: ['leggings', 'women', 'training', 'seamless'],
    images: [],
    price: 449,
    compareAtPrice: 549,
    currencyCode: 'DKK',
    variants: [
      {id: 'v-xs', title: 'XS', available: true},
      {id: 'v-s', title: 'S', available: true},
      {id: 'v-m', title: 'M', available: true},
      {id: 'v-l', title: 'L', available: false},
    ],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/gymshark/seamless-legging?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'partnerize',
    featured: true,
    popular: true,
    available: true,
    createdAt: iso(40),
    updatedAt: iso(2),
  },
  {
    id: 'prod_nike_dry_tee',
    handle: 'nike-dri-fit-training-tee',
    title: 'Dri-FIT Training Tee',
    description: 'Lightweight moisture-wicking tee for high-intensity gym sessions.',
    brand: 'Nike Training',
    brandId: 'brand-nike',
    category: 'activewear',
    tags: ['tee', 'men', 'dri-fit'],
    images: [],
    price: 299,
    compareAtPrice: null,
    currencyCode: 'DKK',
    variants: [
      {id: 'v-s', title: 'S', available: true},
      {id: 'v-m', title: 'M', available: true},
      {id: 'v-l', title: 'L', available: true},
      {id: 'v-xl', title: 'XL', available: true},
    ],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/nike/dri-fit-tee?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'awin',
    featured: true,
    popular: true,
    available: true,
    createdAt: iso(30),
    updatedAt: iso(5),
  },
  {
    id: 'prod_rogue_kb_24',
    handle: 'rogue-kettlebell-24kg',
    title: 'Cast Iron Kettlebell 24 kg',
    description: 'Single-piece cast iron kettlebell with colour-coded handle for home or garage gyms.',
    brand: 'Rogue',
    brandId: 'brand-rogue',
    category: 'equipment',
    tags: ['kettlebell', 'strength', 'home-gym'],
    images: [],
    price: 899,
    compareAtPrice: 999,
    currencyCode: 'DKK',
    variants: [{id: 'v-24', title: '24 kg', available: true}],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/rogue/kb-24?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'impact',
    featured: true,
    popular: true,
    available: true,
    createdAt: iso(60),
    updatedAt: iso(8),
  },
  {
    id: 'prod_rogue_ab_mat',
    handle: 'rogue-ab-mat',
    title: 'Ab Mat',
    description: 'Supportive ab mat for sit-ups and core circuits without floor pressure on the spine.',
    brand: 'Rogue',
    brandId: 'brand-rogue',
    category: 'equipment',
    tags: ['core', 'mat', 'crossfit'],
    images: [],
    price: 279,
    compareAtPrice: null,
    currencyCode: 'DKK',
    variants: [{id: 'v-std', title: 'Standard', available: true}],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/rogue/ab-mat?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'impact',
    featured: false,
    popular: true,
    available: true,
    createdAt: iso(55),
    updatedAt: iso(12),
  },
  {
    id: 'prod_mp_whey',
    handle: 'myprotein-impact-whey',
    title: 'Impact Whey Protein 1 kg',
    description: 'Everyday whey concentrate with 21 g protein per serving — Chocolate Smooth.',
    brand: 'Myprotein',
    brandId: 'brand-myprotein',
    category: 'supplements',
    tags: ['protein', 'whey', 'chocolate'],
    images: [],
    price: 249,
    compareAtPrice: 299,
    currencyCode: 'DKK',
    variants: [
      {id: 'v-choc', title: 'Chocolate', available: true},
      {id: 'v-van', title: 'Vanilla', available: true},
      {id: 'v-straw', title: 'Strawberry', available: false},
    ],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/myprotein/impact-whey?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'awin',
    featured: true,
    popular: true,
    available: true,
    createdAt: iso(20),
    updatedAt: iso(1),
  },
  {
    id: 'prod_mp_creatine',
    handle: 'myprotein-creatine-monohydrate',
    title: 'Creatine Monohydrate 250 g',
    description: 'Unflavoured micronised creatine for strength and power phases.',
    brand: 'Myprotein',
    brandId: 'brand-myprotein',
    category: 'supplements',
    tags: ['creatine', 'strength'],
    images: [],
    price: 129,
    compareAtPrice: null,
    currencyCode: 'DKK',
    variants: [{id: 'v-250', title: '250 g', available: true}],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/myprotein/creatine?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'awin',
    featured: false,
    popular: true,
    available: true,
    createdAt: iso(18),
    updatedAt: iso(3),
  },
  {
    id: 'prod_thera_mini',
    handle: 'theragun-mini-3',
    title: 'Theragun Mini 3rd Gen',
    description: 'Portable percussion massage device for post-workout recovery on the go.',
    brand: 'Therabody',
    brandId: 'brand-theragun',
    category: 'recovery',
    tags: ['massage', 'recovery', 'percussion'],
    images: [],
    price: 1499,
    compareAtPrice: 1699,
    currencyCode: 'DKK',
    variants: [
      {id: 'v-black', title: 'Black', available: true},
      {id: 'v-red', title: 'Red', available: true},
    ],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/therabody/mini-3?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'partnerize',
    featured: true,
    popular: false,
    available: true,
    createdAt: iso(25),
    updatedAt: iso(4),
  },
  {
    id: 'prod_foam_roller',
    handle: 'gymly-foam-roller',
    title: 'Gymly High-Density Foam Roller',
    description: 'Firm foam roller for mobility work between sessions — Gymly exclusive.',
    brand: 'Gymly',
    brandId: 'brand-gymly',
    category: 'recovery',
    tags: ['foam-roller', 'mobility', 'gymly'],
    images: [],
    price: 199,
    compareAtPrice: null,
    currencyCode: 'DKK',
    variants: [{id: 'v-std', title: 'Standard', available: true}],
    salesModel: 'gymly',
    destinationUrl: 'https://shop.gymlyapp.com/products/gymly-foam-roller',
    affiliateTrackingStatus: null,
    affiliateNetwork: null,
    featured: true,
    popular: true,
    available: true,
    createdAt: iso(10),
    updatedAt: iso(1),
  },
  {
    id: 'prod_lifting_straps',
    handle: 'gymly-lifting-straps',
    title: 'Gymly Lifting Straps',
    description: 'Cotton lifting straps with reinforced stitching for heavy pulls.',
    brand: 'Gymly',
    brandId: 'brand-gymly',
    category: 'accessories',
    tags: ['straps', 'lifting', 'gymly'],
    images: [],
    price: 149,
    compareAtPrice: 179,
    currencyCode: 'DKK',
    variants: [{id: 'v-pair', title: 'Pair', available: true}],
    salesModel: 'gymly',
    destinationUrl: 'https://shop.gymlyapp.com/products/gymly-lifting-straps',
    affiliateTrackingStatus: null,
    affiliateNetwork: null,
    featured: false,
    popular: true,
    available: true,
    createdAt: iso(14),
    updatedAt: iso(6),
  },
  {
    id: 'prod_shaker',
    handle: 'gymly-protein-shaker',
    title: 'Gymly Protein Shaker 700 ml',
    description: 'Leak-resistant shaker with mixing grid — Gymly brand colours.',
    brand: 'Gymly',
    brandId: 'brand-gymly',
    category: 'accessories',
    tags: ['shaker', 'bottle', 'gymly'],
    images: [],
    price: 99,
    compareAtPrice: null,
    currencyCode: 'DKK',
    variants: [
      {id: 'v-purple', title: 'Purple', available: true},
      {id: 'v-black', title: 'Black', available: true},
    ],
    salesModel: 'gymly',
    destinationUrl: 'https://shop.gymlyapp.com/products/gymly-protein-shaker',
    affiliateTrackingStatus: null,
    affiliateNetwork: null,
    featured: false,
    popular: false,
    available: true,
    createdAt: iso(7),
    updatedAt: iso(2),
  },
  {
    id: 'prod_gs_sports_bra',
    handle: 'gymshark-vital-seamless-bra',
    title: 'Vital Seamless Sports Bra',
    description: 'Medium-support seamless sports bra with contoured cups for training.',
    brand: 'Gymshark',
    brandId: 'brand-gymshark',
    category: 'activewear',
    tags: ['bra', 'women', 'support'],
    images: [],
    price: 329,
    compareAtPrice: null,
    currencyCode: 'DKK',
    variants: [
      {id: 'v-xs', title: 'XS', available: true},
      {id: 'v-s', title: 'S', available: true},
      {id: 'v-m', title: 'M', available: false},
    ],
    salesModel: 'affiliate',
    destinationUrl: 'https://example.com/affiliate/gymshark/vital-bra?aff_id=gymly-local&utm_source=gymly',
    affiliateTrackingStatus: 'configured',
    affiliateNetwork: 'partnerize',
    featured: false,
    popular: true,
    available: true,
    createdAt: iso(22),
    updatedAt: iso(9),
  },
  {
    id: 'prod_resistance_bands',
    handle: 'gymly-resistance-band-set',
    title: 'Gymly Resistance Band Set',
    description: 'Three-level loop band set for warm-ups, activation and travel sessions.',
    brand: 'Gymly',
    brandId: 'brand-gymly',
    category: 'equipment',
    tags: ['bands', 'mobility', 'travel', 'gymly'],
    images: [],
    price: 179,
    compareAtPrice: 219,
    currencyCode: 'DKK',
    variants: [{id: 'v-set', title: 'Set of 3', available: true}],
    salesModel: 'gymly',
    destinationUrl: 'https://shop.gymlyapp.com/products/gymly-resistance-band-set',
    affiliateTrackingStatus: null,
    affiliateNetwork: null,
    featured: true,
    popular: false,
    available: true,
    createdAt: iso(9),
    updatedAt: iso(1),
  },
];
